# https://taskfile.dev

version: '3'

tasks:
  bash:
    - cat input-2.txt | ./bash.sh
  python:
    - cat input-2.txt | ./python.py
  elixir:
    - cat input-2.txt | ./elixir.exs
  golang:
    - cat input-2.txt | go run golang.go
  rust:
    - cat input-2.txt | cargo run
